CREATE TYPE public.app_role AS ENUM ('admin','instructor','student');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL DEFAULT 'student', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
CREATE TABLE public.profiles (id uuid PRIMARY KEY, display_name text NOT NULL DEFAULT 'New learner', avatar_url text, headline text, timezone text NOT NULL DEFAULT 'Asia/Kolkata', preferences jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.courses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, title text NOT NULL, slug text NOT NULL UNIQUE, description text NOT NULL DEFAULT '', category text NOT NULL DEFAULT 'Technology', thumbnail_path text, instructor_name text NOT NULL DEFAULT 'StreamX Instructor', visibility text NOT NULL DEFAULT 'draft' CHECK(visibility IN ('draft','published','archived')), price_cents integer NOT NULL DEFAULT 0 CHECK(price_cents>=0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.courses TO anon;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.courses TO authenticated;
GRANT ALL ON public.courses TO service_role;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.modules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), course_id uuid NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE, title text NOT NULL, position integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.modules TO authenticated;
GRANT ALL ON public.modules TO service_role;
ALTER TABLE public.modules ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.videos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, course_id uuid REFERENCES public.courses(id) ON DELETE SET NULL, title text NOT NULL, description text NOT NULL DEFAULT '', category text NOT NULL DEFAULT 'General', visibility text NOT NULL DEFAULT 'private' CHECK(visibility IN ('private','unlisted','published')), source_path text, thumbnail_path text, duration_seconds integer NOT NULL DEFAULT 0 CHECK(duration_seconds>=0), original_size_bytes bigint NOT NULL DEFAULT 0 CHECK(original_size_bytes>=0), status text NOT NULL DEFAULT 'uploaded' CHECK(status IN ('uploaded','queued','processing','ready','failed')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.videos TO authenticated;
GRANT ALL ON public.videos TO service_role;
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.lessons (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), module_id uuid NOT NULL REFERENCES public.modules(id) ON DELETE CASCADE, title text NOT NULL, duration_seconds integer NOT NULL DEFAULT 0 CHECK(duration_seconds>=0), video_id uuid REFERENCES public.videos(id) ON DELETE SET NULL, position integer NOT NULL DEFAULT 0, preview_enabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.lessons TO authenticated;
GRANT ALL ON public.lessons TO service_role;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.video_variants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), video_id uuid NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE, quality text NOT NULL, width integer NOT NULL DEFAULT 0, height integer NOT NULL DEFAULT 0, bitrate_kbps integer NOT NULL DEFAULT 0, size_bytes bigint NOT NULL DEFAULT 0, manifest_path text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(video_id,quality));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.video_variants TO authenticated;
GRANT ALL ON public.video_variants TO service_role;
ALTER TABLE public.video_variants ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.video_processing_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), video_id uuid NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','validating','transcoding','packaging','complete','failed')), progress_percent integer NOT NULL DEFAULT 0 CHECK(progress_percent BETWEEN 0 AND 100), stage text NOT NULL DEFAULT 'Queued', error_message text, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.video_processing_jobs TO authenticated;
GRANT ALL ON public.video_processing_jobs TO service_role;
ALTER TABLE public.video_processing_jobs ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.enrollments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, course_id uuid NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','completed','cancelled')), enrolled_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,course_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.enrollments TO authenticated;
GRANT ALL ON public.enrollments TO service_role;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.watch_progress (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, lesson_id uuid NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE, last_position_seconds integer NOT NULL DEFAULT 0 CHECK(last_position_seconds>=0), watched_seconds bigint NOT NULL DEFAULT 0, completion_percent numeric(5,2) NOT NULL DEFAULT 0 CHECK(completion_percent BETWEEN 0 AND 100), completed_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,lesson_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.watch_progress TO authenticated;
GRANT ALL ON public.watch_progress TO service_role;
ALTER TABLE public.watch_progress ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.analytics_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, video_id uuid REFERENCES public.videos(id) ON DELETE SET NULL, course_id uuid REFERENCES public.courses(id) ON DELETE SET NULL, event_name text NOT NULL, region text, quality text, device_type text, payload jsonb NOT NULL DEFAULT '{}'::jsonb, occurred_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.analytics_events TO authenticated;
GRANT ALL ON public.analytics_events TO service_role;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.bandwidth_usage (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, video_id uuid REFERENCES public.videos(id) ON DELETE SET NULL, region text NOT NULL DEFAULT 'Global', bytes_served bigint NOT NULL DEFAULT 0 CHECK(bytes_served>=0), edge_bytes bigint NOT NULL DEFAULT 0 CHECK(edge_bytes>=0), origin_bytes bigint NOT NULL DEFAULT 0 CHECK(origin_bytes>=0), recorded_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.bandwidth_usage TO authenticated;
GRANT ALL ON public.bandwidth_usage TO service_role;
ALTER TABLE public.bandwidth_usage ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.cache_metrics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, region text NOT NULL DEFAULT 'Global', hit_count bigint NOT NULL DEFAULT 0, miss_count bigint NOT NULL DEFAULT 0, bytes_saved bigint NOT NULL DEFAULT 0, recorded_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.cache_metrics TO authenticated;
GRANT ALL ON public.cache_metrics TO service_role;
ALTER TABLE public.cache_metrics ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.storage_usage (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, video_id uuid REFERENCES public.videos(id) ON DELETE SET NULL, stored_bytes bigint NOT NULL DEFAULT 0, storage_class text NOT NULL DEFAULT 'standard', recorded_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.storage_usage TO authenticated;
GRANT ALL ON public.storage_usage TO service_role;
ALTER TABLE public.storage_usage ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.infrastructure_nodes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, name text NOT NULL, region text NOT NULL, node_type text NOT NULL DEFAULT 'edge', health text NOT NULL DEFAULT 'healthy' CHECK(health IN ('healthy','warning','critical')), cpu_percent numeric(5,2) NOT NULL DEFAULT 0, memory_percent numeric(5,2) NOT NULL DEFAULT 0, latency_ms numeric(8,2) NOT NULL DEFAULT 0, requests_per_second numeric(10,2) NOT NULL DEFAULT 0, recorded_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.infrastructure_nodes TO authenticated;
GRANT ALL ON public.infrastructure_nodes TO service_role;
ALTER TABLE public.infrastructure_nodes ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.cost_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, category text NOT NULL, amount_cents bigint NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'INR', period_start date NOT NULL DEFAULT current_date, period_end date NOT NULL DEFAULT current_date, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.cost_records TO authenticated;
GRANT ALL ON public.cost_records TO service_role;
ALTER TABLE public.cost_records ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, plan text NOT NULL DEFAULT 'starter', status text NOT NULL DEFAULT 'demo' CHECK(status IN ('trialing','active','past_due','cancelled','demo')), provider_customer_id text, period_end timestamptz, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.subscriptions TO authenticated;
GRANT ALL ON public.subscriptions TO service_role;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, subscription_id uuid REFERENCES public.subscriptions(id) ON DELETE SET NULL, amount_cents bigint NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'INR', status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','paid','failed','refunded')), provider_reference text, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.payments TO authenticated;
GRANT ALL ON public.payments TO service_role;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.api_keys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, label text NOT NULL, key_prefix text NOT NULL, key_hash text NOT NULL, revoked_at timestamptz, last_used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.api_keys TO authenticated;
GRANT ALL ON public.api_keys TO service_role;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.assign_student_role_to_new_profile() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.user_roles(user_id,role) VALUES(NEW.id,'student') ON CONFLICT(user_id,role) DO NOTHING; RETURN NEW; END; $$;
CREATE TRIGGER assign_student_role_after_profile_creation AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.assign_student_role_to_new_profile();
CREATE POLICY "Own profile or admin read" ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Own profile create" ON public.profiles FOR INSERT TO authenticated WITH CHECK(id=auth.uid());
CREATE POLICY "Own profile or admin update" ON public.profiles FOR UPDATE TO authenticated USING(id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Users read own role" ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Published courses are public" ON public.courses FOR SELECT USING(visibility='published');
CREATE POLICY "Course owner or admin manages" ON public.courses FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Course modules public read" ON public.modules FOR SELECT USING(EXISTS(SELECT 1 FROM public.courses c WHERE c.id=course_id AND c.visibility='published'));
CREATE POLICY "Course owner manages modules" ON public.modules FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.courses c WHERE c.id=course_id AND (c.owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)))) WITH CHECK(EXISTS(SELECT 1 FROM public.courses c WHERE c.id=course_id AND (c.owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role))));
CREATE POLICY "Course lessons public read" ON public.lessons FOR SELECT USING(EXISTS(SELECT 1 FROM public.modules m JOIN public.courses c ON c.id=m.course_id WHERE m.id=module_id AND c.visibility='published' AND preview_enabled));
CREATE POLICY "Course owner manages lessons" ON public.lessons FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.modules m JOIN public.courses c ON c.id=m.course_id WHERE m.id=module_id AND (c.owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)))) WITH CHECK(EXISTS(SELECT 1 FROM public.modules m JOIN public.courses c ON c.id=m.course_id WHERE m.id=module_id AND (c.owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role))));
CREATE POLICY "Video owner manages" ON public.videos FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Video owner manages variants" ON public.video_variants FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.videos v WHERE v.id=video_id AND (v.owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)))) WITH CHECK(EXISTS(SELECT 1 FROM public.videos v WHERE v.id=video_id AND (v.owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role))));
CREATE POLICY "Video owner manages processing" ON public.video_processing_jobs FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.videos v WHERE v.id=video_id AND (v.owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)))) WITH CHECK(EXISTS(SELECT 1 FROM public.videos v WHERE v.id=video_id AND (v.owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role))));
CREATE POLICY "Own enrollments" ON public.enrollments FOR ALL TO authenticated USING(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Own watch progress" ON public.watch_progress FOR ALL TO authenticated USING(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Owner analytics events" ON public.analytics_events FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Owner bandwidth data" ON public.bandwidth_usage FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Owner cache metrics" ON public.cache_metrics FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Owner storage metrics" ON public.storage_usage FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Owner infrastructure nodes" ON public.infrastructure_nodes FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Owner cost records" ON public.cost_records FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Own subscriptions" ON public.subscriptions FOR ALL TO authenticated USING(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Own payment history" ON public.payments FOR ALL TO authenticated USING(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(user_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE POLICY "Own API credentials" ON public.api_keys FOR ALL TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role)) WITH CHECK(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'::public.app_role));
CREATE INDEX courses_owner_created_idx ON public.courses(owner_id,created_at DESC);
CREATE INDEX videos_owner_created_idx ON public.videos(owner_id,created_at DESC);
CREATE INDEX videos_course_idx ON public.videos(course_id);
CREATE INDEX modules_course_position_idx ON public.modules(course_id,position);
CREATE INDEX lessons_module_position_idx ON public.lessons(module_id,position);
CREATE INDEX video_variants_video_idx ON public.video_variants(video_id);
CREATE INDEX processing_jobs_video_status_idx ON public.video_processing_jobs(video_id,status);
CREATE INDEX enrollments_user_idx ON public.enrollments(user_id,enrolled_at DESC);
CREATE INDEX watch_progress_user_updated_idx ON public.watch_progress(user_id,updated_at DESC);
CREATE INDEX analytics_events_owner_time_idx ON public.analytics_events(owner_id,occurred_at DESC);
CREATE INDEX bandwidth_owner_time_idx ON public.bandwidth_usage(owner_id,recorded_at DESC);
CREATE INDEX cache_owner_time_idx ON public.cache_metrics(owner_id,recorded_at DESC);
CREATE INDEX storage_owner_time_idx ON public.storage_usage(owner_id,recorded_at DESC);
CREATE INDEX nodes_owner_region_idx ON public.infrastructure_nodes(owner_id,region);
CREATE INDEX costs_owner_period_idx ON public.cost_records(owner_id,period_start DESC);
CREATE INDEX api_keys_owner_created_idx ON public.api_keys(owner_id,created_at DESC);
CREATE POLICY "Private video uploads by owner" ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id='streamx-media' AND (storage.foldername(name))[1]=auth.uid()::text);
CREATE POLICY "Private video reads by owner" ON storage.objects FOR SELECT TO authenticated USING(bucket_id='streamx-media' AND ((storage.foldername(name))[1]=auth.uid()::text OR public.has_role(auth.uid(),'admin'::public.app_role)));
CREATE POLICY "Private video updates by owner" ON storage.objects FOR UPDATE TO authenticated USING(bucket_id='streamx-media' AND ((storage.foldername(name))[1]=auth.uid()::text OR public.has_role(auth.uid(),'admin'::public.app_role))) WITH CHECK(bucket_id='streamx-media' AND ((storage.foldername(name))[1]=auth.uid()::text OR public.has_role(auth.uid(),'admin'::public.app_role)));
CREATE POLICY "Private video deletes by owner" ON storage.objects FOR DELETE TO authenticated USING(bucket_id='streamx-media' AND ((storage.foldername(name))[1]=auth.uid()::text OR public.has_role(auth.uid(),'admin'::public.app_role)));